// Generated by gencpp from file flapper/Rpm.msg
// DO NOT EDIT!


#ifndef FLAPPER_MESSAGE_RPM_H
#define FLAPPER_MESSAGE_RPM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flapper
{
template <class ContainerAllocator>
struct Rpm_
{
  typedef Rpm_<ContainerAllocator> Type;

  Rpm_()
    : m1(0)
    , m2(0)
    , m3(0)
    , m4(0)  {
    }
  Rpm_(const ContainerAllocator& _alloc)
    : m1(0)
    , m2(0)
    , m3(0)
    , m4(0)  {
  (void)_alloc;
    }



   typedef uint16_t _m1_type;
  _m1_type m1;

   typedef uint16_t _m2_type;
  _m2_type m2;

   typedef uint16_t _m3_type;
  _m3_type m3;

   typedef uint16_t _m4_type;
  _m4_type m4;





  typedef boost::shared_ptr< ::flapper::Rpm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flapper::Rpm_<ContainerAllocator> const> ConstPtr;

}; // struct Rpm_

typedef ::flapper::Rpm_<std::allocator<void> > Rpm;

typedef boost::shared_ptr< ::flapper::Rpm > RpmPtr;
typedef boost::shared_ptr< ::flapper::Rpm const> RpmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flapper::Rpm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flapper::Rpm_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flapper::Rpm_<ContainerAllocator1> & lhs, const ::flapper::Rpm_<ContainerAllocator2> & rhs)
{
  return lhs.m1 == rhs.m1 &&
    lhs.m2 == rhs.m2 &&
    lhs.m3 == rhs.m3 &&
    lhs.m4 == rhs.m4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flapper::Rpm_<ContainerAllocator1> & lhs, const ::flapper::Rpm_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flapper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flapper::Rpm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flapper::Rpm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flapper::Rpm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flapper::Rpm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flapper::Rpm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flapper::Rpm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flapper::Rpm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29ed5a63544f3887c01e281980c939e1";
  }

  static const char* value(const ::flapper::Rpm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29ed5a63544f3887ULL;
  static const uint64_t static_value2 = 0xc01e281980c939e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::flapper::Rpm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flapper/Rpm";
  }

  static const char* value(const ::flapper::Rpm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flapper::Rpm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 m1\n"
"uint16 m2\n"
"uint16 m3\n"
"uint16 m4\n"
;
  }

  static const char* value(const ::flapper::Rpm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flapper::Rpm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.m1);
      stream.next(m.m2);
      stream.next(m.m3);
      stream.next(m.m4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rpm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flapper::Rpm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flapper::Rpm_<ContainerAllocator>& v)
  {
    s << indent << "m1: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.m1);
    s << indent << "m2: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.m2);
    s << indent << "m3: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.m3);
    s << indent << "m4: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.m4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLAPPER_MESSAGE_RPM_H
