// Generated by gencpp from file flapper/Stabilizer.msg
// DO NOT EDIT!


#ifndef FLAPPER_MESSAGE_STABILIZER_H
#define FLAPPER_MESSAGE_STABILIZER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flapper
{
template <class ContainerAllocator>
struct Stabilizer_
{
  typedef Stabilizer_<ContainerAllocator> Type;

  Stabilizer_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , thrust(0.0)  {
    }
  Stabilizer_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , thrust(0.0)  {
  (void)_alloc;
    }



   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _thrust_type;
  _thrust_type thrust;





  typedef boost::shared_ptr< ::flapper::Stabilizer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flapper::Stabilizer_<ContainerAllocator> const> ConstPtr;

}; // struct Stabilizer_

typedef ::flapper::Stabilizer_<std::allocator<void> > Stabilizer;

typedef boost::shared_ptr< ::flapper::Stabilizer > StabilizerPtr;
typedef boost::shared_ptr< ::flapper::Stabilizer const> StabilizerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flapper::Stabilizer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flapper::Stabilizer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flapper::Stabilizer_<ContainerAllocator1> & lhs, const ::flapper::Stabilizer_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.thrust == rhs.thrust;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flapper::Stabilizer_<ContainerAllocator1> & lhs, const ::flapper::Stabilizer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flapper

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flapper::Stabilizer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flapper::Stabilizer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flapper::Stabilizer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flapper::Stabilizer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flapper::Stabilizer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flapper::Stabilizer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flapper::Stabilizer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "028032831aa76f2200dc4a9de4c3b78b";
  }

  static const char* value(const ::flapper::Stabilizer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x028032831aa76f22ULL;
  static const uint64_t static_value2 = 0x00dc4a9de4c3b78bULL;
};

template<class ContainerAllocator>
struct DataType< ::flapper::Stabilizer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flapper/Stabilizer";
  }

  static const char* value(const ::flapper::Stabilizer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flapper::Stabilizer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"float64 thrust\n"
;
  }

  static const char* value(const ::flapper::Stabilizer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flapper::Stabilizer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.thrust);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Stabilizer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flapper::Stabilizer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flapper::Stabilizer_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "thrust: ";
    Printer<double>::stream(s, indent + "  ", v.thrust);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLAPPER_MESSAGE_STABILIZER_H
